version: "3.9"

services:
  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  backend:
    build: ./CRM/BackEnd
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/MiniCRM
    depends_on:
      - mongodb
    networks:
      - mern-network

  frontend:
    build: ./CRM/frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
